steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-west1-docker.pkg.dev/lab01-400515/lab01-repo/info-host:1.0', './docker']
  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west1-docker.pkg.dev/lab01-400515/lab01-repo/info-host:1.0']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['rollout', 'restart', 'deployment', 'info-host:1.0']
    env:
      - CLOUDSDK_CONTAINER_CLUSTER=lab01
      - CLOUDSDK_COMPUTE_ZONE=us-west1-a
      - CLOUDSDK_COMPUTE_REGION=us-west1
options:
  logging: CLOUD_LOGGING_ONLY